CREATE DATABASE IF NOT EXISTS supplier_collaboration DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;
USE supplier_collaboration;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS sys_config;
DROP TABLE IF EXISTS sys_audit_log;
DROP TABLE IF EXISTS sys_login_log;
DROP TABLE IF EXISTS sys_file_attachment;
DROP TABLE IF EXISTS sys_idempotent_record;
DROP TABLE IF EXISTS sys_export_task;
DROP TABLE IF EXISTS sys_user_role;
DROP TABLE IF EXISTS sys_role_permission;
DROP TABLE IF EXISTS sys_dict_item;
DROP TABLE IF EXISTS sys_dict;
DROP TABLE IF EXISTS sys_permission;
DROP TABLE IF EXISTS sys_role;
DROP TABLE IF EXISTS sys_user;
DROP TABLE IF EXISTS supplier_contact;
DROP TABLE IF EXISTS supplier_bank_account;
DROP TABLE IF EXISTS supplier_blacklist;
DROP TABLE IF EXISTS supplier_qualification;
DROP TABLE IF EXISTS supplier_performance;
DROP TABLE IF EXISTS supplier_category;
DROP TABLE IF EXISTS supplier_info;
DROP TABLE IF EXISTS material_info;
DROP TABLE IF EXISTS rfq_supplier;
DROP TABLE IF EXISTS quote_item;
DROP TABLE IF EXISTS quote;
DROP TABLE IF EXISTS rfq_item;
DROP TABLE IF EXISTS rfq;
DROP TABLE IF EXISTS purchase_order_detail;
DROP TABLE IF EXISTS purchase_order;
DROP TABLE IF EXISTS delivery_plan;
DROP TABLE IF EXISTS order_change;
DROP TABLE IF EXISTS order_status_log;
DROP TABLE IF EXISTS order_track;
DROP TABLE IF EXISTS delivery_label;
DROP TABLE IF EXISTS delivery_detail;
DROP TABLE IF EXISTS delivery_notice;
DROP TABLE IF EXISTS receipt_record;
DROP TABLE IF EXISTS vmi_inventory;
DROP TABLE IF EXISTS forecast_demand;
DROP TABLE IF EXISTS inspection_standard_item;
DROP TABLE IF EXISTS inspection_standard;
DROP TABLE IF EXISTS quality_inspection;
DROP TABLE IF EXISTS nonconformance_report;
DROP TABLE IF EXISTS eight_d_report;
DROP TABLE IF EXISTS quality_appeal;
DROP TABLE IF EXISTS deduction;
DROP TABLE IF EXISTS reconciliation_detail;
DROP TABLE IF EXISTS reconciliation;
DROP TABLE IF EXISTS invoice;
DROP TABLE IF EXISTS payment;
DROP TABLE IF EXISTS portal_todo;
DROP TABLE IF EXISTS message_notice;
DROP TABLE IF EXISTS message_event_log;
DROP TABLE IF EXISTS integration_endpoint;
DROP TABLE IF EXISTS integration_log;
DROP TABLE IF EXISTS integration_sync_task;

CREATE TABLE sys_user (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    org_id BIGINT DEFAULT NULL COMMENT '组织ID',
    username VARCHAR(50) NOT NULL COMMENT '用户名',
    password VARCHAR(100) NOT NULL COMMENT '密码哈希',
    real_name VARCHAR(50) DEFAULT NULL COMMENT '真实姓名',
    phone VARCHAR(20) DEFAULT NULL COMMENT '手机号',
    email VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
    avatar VARCHAR(500) DEFAULT NULL COMMENT '头像URL',
    user_type TINYINT NOT NULL DEFAULT 1 COMMENT '用户类型(1内部用户,2供应商用户,3接口账号)',
    supplier_id BIGINT DEFAULT NULL COMMENT '供应商ID',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态(0禁用,1启用,2锁定)',
    password_update_time DATETIME DEFAULT NULL COMMENT '密码更新时间',
    last_login_time DATETIME DEFAULT NULL COMMENT '最后登录时间',
    last_login_ip VARCHAR(50) DEFAULT NULL COMMENT '最后登录IP',
    token_version INT NOT NULL DEFAULT 0 COMMENT '令牌版本',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除(0未删除,1已删除)',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_username (username),
    KEY idx_supplier_status (supplier_id,status),
    KEY idx_org_status (org_id,status),
    KEY idx_phone (phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户表';

CREATE TABLE sys_role (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    role_name VARCHAR(50) NOT NULL COMMENT '角色名称',
    role_code VARCHAR(50) NOT NULL COMMENT '角色编码',
    role_type TINYINT NOT NULL DEFAULT 1 COMMENT '角色类型(1内部,2供应商,3接口)',
    data_scope TINYINT NOT NULL DEFAULT 1 COMMENT '数据范围(1全部,2组织,3本人,4供应商)',
    description VARCHAR(255) DEFAULT NULL COMMENT '角色描述',
    sort INT NOT NULL DEFAULT 0 COMMENT '排序',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态(0禁用,1启用)',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_role_code (role_code),
    KEY idx_status_sort (status,sort)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='角色表';

CREATE TABLE sys_permission (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    parent_id BIGINT NOT NULL DEFAULT 0 COMMENT '父级ID',
    perm_name VARCHAR(50) NOT NULL COMMENT '权限名称',
    perm_code VARCHAR(100) NOT NULL COMMENT '权限编码',
    perm_type TINYINT NOT NULL COMMENT '权限类型(1菜单,2按钮,3接口)',
    path VARCHAR(255) DEFAULT NULL COMMENT '路由或接口路径',
    component VARCHAR(255) DEFAULT NULL COMMENT '组件路径',
    http_method VARCHAR(20) DEFAULT NULL COMMENT 'HTTP方法',
    icon VARCHAR(100) DEFAULT NULL COMMENT '图标',
    sort INT NOT NULL DEFAULT 0 COMMENT '排序',
    visible TINYINT NOT NULL DEFAULT 1 COMMENT '是否可见',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_perm_code (perm_code),
    KEY idx_parent_sort (parent_id,sort),
    KEY idx_type_status (perm_type,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='权限表';

CREATE TABLE sys_user_role (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    role_id BIGINT NOT NULL COMMENT '角色ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_role (user_id,role_id),
    KEY idx_role_id (role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户角色关联表';

CREATE TABLE sys_role_permission (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    role_id BIGINT NOT NULL COMMENT '角色ID',
    perm_id BIGINT NOT NULL COMMENT '权限ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_role_perm (role_id,perm_id),
    KEY idx_perm_id (perm_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='角色权限关联表';

CREATE TABLE sys_dict (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    dict_name VARCHAR(50) NOT NULL COMMENT '字典名称',
    dict_code VARCHAR(50) NOT NULL COMMENT '字典编码',
    description VARCHAR(255) DEFAULT NULL COMMENT '字典描述',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_dict_code (dict_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='数据字典表';

CREATE TABLE sys_dict_item (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    dict_id BIGINT NOT NULL COMMENT '字典ID',
    item_label VARCHAR(50) NOT NULL COMMENT '字典项标签',
    item_value VARCHAR(50) NOT NULL COMMENT '字典项值',
    sort INT NOT NULL DEFAULT 0 COMMENT '排序',
    description VARCHAR(255) DEFAULT NULL COMMENT '描述',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_dict_item (dict_id,item_value),
    KEY idx_dict_sort (dict_id,sort)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='字典项表';

CREATE TABLE sys_config (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    config_name VARCHAR(100) NOT NULL COMMENT '参数名称',
    config_key VARCHAR(100) NOT NULL COMMENT '参数键',
    config_value VARCHAR(1000) DEFAULT NULL COMMENT '参数值',
    config_type TINYINT NOT NULL DEFAULT 1 COMMENT '参数类型(1系统,2业务)',
    encrypted TINYINT NOT NULL DEFAULT 0 COMMENT '是否加密',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_config_key (config_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='系统参数表';

CREATE TABLE sys_audit_log (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    trace_id VARCHAR(100) DEFAULT NULL COMMENT '链路ID',
    user_id BIGINT DEFAULT NULL COMMENT '用户ID',
    username VARCHAR(50) DEFAULT NULL COMMENT '用户名',
    module_name VARCHAR(50) DEFAULT NULL COMMENT '模块名称',
    business_type VARCHAR(50) DEFAULT NULL COMMENT '业务类型',
    business_id BIGINT DEFAULT NULL COMMENT '业务ID',
    business_no VARCHAR(50) DEFAULT NULL COMMENT '业务单号',
    action_name VARCHAR(50) NOT NULL COMMENT '操作动作',
    before_status TINYINT DEFAULT NULL COMMENT '变更前状态',
    after_status TINYINT DEFAULT NULL COMMENT '变更后状态',
    request_method VARCHAR(20) DEFAULT NULL COMMENT '请求方法',
    request_path VARCHAR(255) DEFAULT NULL COMMENT '请求路径',
    client_ip VARCHAR(50) DEFAULT NULL COMMENT '客户端IP',
    result_status TINYINT NOT NULL DEFAULT 1 COMMENT '结果(0失败,1成功)',
    error_message VARCHAR(500) DEFAULT NULL COMMENT '错误信息',
    operate_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_business (business_type,business_id),
    KEY idx_user_time (user_id,operate_time),
    KEY idx_trace_id (trace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='审计日志表';

CREATE TABLE sys_login_log (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    username VARCHAR(50) DEFAULT NULL COMMENT '用户名',
    user_id BIGINT DEFAULT NULL COMMENT '用户ID',
    login_type TINYINT NOT NULL DEFAULT 1 COMMENT '登录类型(1密码,2刷新令牌)',
    client_ip VARCHAR(50) DEFAULT NULL COMMENT '客户端IP',
    user_agent VARCHAR(500) DEFAULT NULL COMMENT '用户代理',
    login_status TINYINT NOT NULL DEFAULT 1 COMMENT '登录状态(0失败,1成功)',
    fail_reason VARCHAR(500) DEFAULT NULL COMMENT '失败原因',
    login_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登录时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_username_time (username,login_time),
    KEY idx_ip_time (client_ip,login_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='登录日志表';

CREATE TABLE sys_file_attachment (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    business_type VARCHAR(50) NOT NULL COMMENT '业务类型',
    business_id BIGINT DEFAULT NULL COMMENT '业务ID',
    business_no VARCHAR(50) DEFAULT NULL COMMENT '业务单号',
    file_name VARCHAR(255) NOT NULL COMMENT '原始文件名',
    file_ext VARCHAR(20) DEFAULT NULL COMMENT '文件扩展名',
    file_size BIGINT NOT NULL DEFAULT 0 COMMENT '文件大小',
    content_type VARCHAR(100) DEFAULT NULL COMMENT 'MIME类型',
    bucket_name VARCHAR(100) NOT NULL COMMENT '存储桶',
    object_key VARCHAR(500) NOT NULL COMMENT '对象Key',
    file_hash VARCHAR(100) DEFAULT NULL COMMENT '文件摘要',
    upload_user_id BIGINT DEFAULT NULL COMMENT '上传用户ID',
    upload_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '上传时间',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态(0禁用,1有效)',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_business (business_type,business_id),
    KEY idx_file_hash (file_hash),
    KEY idx_bucket_object (bucket_name,object_key(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='文件附件表';

CREATE TABLE sys_idempotent_record (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    idempotent_key VARCHAR(100) NOT NULL COMMENT '幂等键',
    business_type VARCHAR(50) NOT NULL COMMENT '业务类型',
    business_id BIGINT DEFAULT NULL COMMENT '业务ID',
    request_hash VARCHAR(100) DEFAULT NULL COMMENT '请求摘要',
    result_code VARCHAR(20) DEFAULT NULL COMMENT '结果码',
    result_message VARCHAR(500) DEFAULT NULL COMMENT '结果信息',
    expire_time DATETIME DEFAULT NULL COMMENT '过期时间',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态(0处理中,1成功,2失败)',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_idempotent_key (idempotent_key),
    KEY idx_business (business_type,business_id),
    KEY idx_expire_time (expire_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='幂等记录表';

CREATE TABLE sys_export_task (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    task_no VARCHAR(50) NOT NULL COMMENT '导出任务号',
    task_type VARCHAR(50) NOT NULL COMMENT '任务类型',
    file_id BIGINT DEFAULT NULL COMMENT '文件ID',
    export_params JSON DEFAULT NULL COMMENT '导出参数',
    total_count INT NOT NULL DEFAULT 0 COMMENT '总数量',
    processed_count INT NOT NULL DEFAULT 0 COMMENT '已处理数量',
    task_status TINYINT NOT NULL DEFAULT 0 COMMENT '任务状态(0待处理,1处理中,2成功,3失败)',
    error_message VARCHAR(500) DEFAULT NULL COMMENT '错误信息',
    start_time DATETIME DEFAULT NULL COMMENT '开始时间',
    finish_time DATETIME DEFAULT NULL COMMENT '完成时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_no (task_no),
    KEY idx_type_status_time (task_type,task_status,create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='异步导出任务表';

CREATE TABLE supplier_category (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    category_name VARCHAR(50) NOT NULL COMMENT '分类名称',
    category_code VARCHAR(50) NOT NULL COMMENT '分类编码',
    parent_id BIGINT NOT NULL DEFAULT 0 COMMENT '父级ID',
    sort INT NOT NULL DEFAULT 0 COMMENT '排序',
    description VARCHAR(255) DEFAULT NULL COMMENT '分类描述',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_category_code (category_code),
    KEY idx_parent_sort (parent_id,sort)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='供应商分类表';

CREATE TABLE supplier_info (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    org_id BIGINT DEFAULT NULL COMMENT '组织ID',
    supplier_code VARCHAR(50) NOT NULL COMMENT '供应商编码',
    supplier_name VARCHAR(100) NOT NULL COMMENT '供应商名称',
    supplier_short_name VARCHAR(50) DEFAULT NULL COMMENT '供应商简称',
    category_id BIGINT DEFAULT NULL COMMENT '分类ID',
    supplier_type TINYINT NOT NULL DEFAULT 1 COMMENT '供应商类型',
    credit_code VARCHAR(50) DEFAULT NULL COMMENT '统一社会信用代码',
    legal_person VARCHAR(50) DEFAULT NULL COMMENT '法人代表',
    registered_capital DECIMAL(18,2) DEFAULT NULL COMMENT '注册资本',
    establish_date DATE DEFAULT NULL COMMENT '成立日期',
    business_scope TEXT DEFAULT NULL COMMENT '经营范围',
    province VARCHAR(50) DEFAULT NULL COMMENT '省份',
    city VARCHAR(50) DEFAULT NULL COMMENT '城市',
    district VARCHAR(50) DEFAULT NULL COMMENT '区县',
    address VARCHAR(255) DEFAULT NULL COMMENT '详细地址',
    contact_name VARCHAR(50) DEFAULT NULL COMMENT '联系人',
    contact_phone VARCHAR(20) DEFAULT NULL COMMENT '联系电话',
    contact_email VARCHAR(100) DEFAULT NULL COMMENT '联系邮箱',
    bank_name VARCHAR(100) DEFAULT NULL COMMENT '开户银行',
    bank_account VARCHAR(50) DEFAULT NULL COMMENT '银行账号',
    tax_number VARCHAR(50) DEFAULT NULL COMMENT '税号',
    invoice_address VARCHAR(255) DEFAULT NULL COMMENT '开票地址',
    invoice_phone VARCHAR(20) DEFAULT NULL COMMENT '开票电话',
    rating TINYINT DEFAULT NULL COMMENT '供应商评级(1A,2B,3C,4D)',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态(0待审核,1合作中,2暂停,3黑名单,4拒绝)',
    submit_time DATETIME DEFAULT NULL COMMENT '提交时间',
    audit_time DATETIME DEFAULT NULL COMMENT '审核时间',
    audit_by BIGINT DEFAULT NULL COMMENT '审核人',
    audit_remark VARCHAR(500) DEFAULT NULL COMMENT '审核备注',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_supplier_code (supplier_code),
    UNIQUE KEY uk_credit_code (credit_code),
    KEY idx_category_status (category_id,status),
    KEY idx_org_status_create_time (org_id,status,create_time),
    KEY idx_name (supplier_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='供应商基本信息表';

CREATE TABLE supplier_contact (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    contact_name VARCHAR(50) NOT NULL COMMENT '联系人姓名',
    contact_role VARCHAR(50) DEFAULT NULL COMMENT '联系人角色',
    contact_phone VARCHAR(20) DEFAULT NULL COMMENT '手机号',
    contact_email VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
    is_primary TINYINT NOT NULL DEFAULT 0 COMMENT '是否主联系人',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_supplier_status (supplier_id,status),
    KEY idx_phone (contact_phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='供应商联系人表';

CREATE TABLE supplier_bank_account (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    account_name VARCHAR(100) NOT NULL COMMENT '账户名称',
    bank_name VARCHAR(100) NOT NULL COMMENT '开户银行',
    bank_branch VARCHAR(100) DEFAULT NULL COMMENT '开户支行',
    bank_account VARCHAR(50) NOT NULL COMMENT '银行账号',
    currency VARCHAR(10) NOT NULL DEFAULT 'CNY' COMMENT '币种',
    is_default TINYINT NOT NULL DEFAULT 0 COMMENT '是否默认',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_supplier_status (supplier_id,status),
    KEY idx_bank_account (bank_account)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='供应商银行账户表';

CREATE TABLE supplier_qualification (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    qual_type VARCHAR(50) NOT NULL COMMENT '资质类型',
    qual_name VARCHAR(100) NOT NULL COMMENT '资质名称',
    qual_no VARCHAR(100) DEFAULT NULL COMMENT '资质编号',
    qual_org VARCHAR(100) DEFAULT NULL COMMENT '发证机构',
    valid_start DATE DEFAULT NULL COMMENT '有效期开始',
    valid_end DATE DEFAULT NULL COMMENT '有效期结束',
    file_id BIGINT DEFAULT NULL COMMENT '附件ID',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态(0无效,1有效,2即将过期,3已过期)',
    remind_days INT NOT NULL DEFAULT 30 COMMENT '提醒天数',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_supplier_type (supplier_id,qual_type),
    KEY idx_valid_end (valid_end),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='供应商资质表';

CREATE TABLE supplier_blacklist (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    supplier_id BIGINT DEFAULT NULL COMMENT '供应商ID',
    supplier_name VARCHAR(100) NOT NULL COMMENT '供应商名称',
    credit_code VARCHAR(50) DEFAULT NULL COMMENT '统一社会信用代码',
    reason VARCHAR(500) NOT NULL COMMENT '拉黑原因',
    start_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '生效时间',
    end_time DATETIME DEFAULT NULL COMMENT '解除时间',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态(0解除,1生效)',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_supplier_status (supplier_id,status),
    KEY idx_credit_code (credit_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='供应商黑名单表';

CREATE TABLE supplier_performance (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    evaluate_period VARCHAR(20) NOT NULL COMMENT '评估周期',
    quality_score DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '质量评分',
    delivery_score DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '交付评分',
    service_score DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '服务评分',
    price_score DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '价格评分',
    total_score DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '综合评分',
    qualified_rate DECIMAL(10,4) DEFAULT NULL COMMENT '合格率',
    ontime_rate DECIMAL(10,4) DEFAULT NULL COMMENT '准交率',
    evaluate_by BIGINT DEFAULT NULL COMMENT '评估人',
    evaluate_time DATETIME DEFAULT NULL COMMENT '评估时间',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_supplier_period (supplier_id,evaluate_period),
    KEY idx_period_score (evaluate_period,total_score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='供应商绩效表';

CREATE TABLE material_info (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    material_code VARCHAR(50) NOT NULL COMMENT '物料编码',
    material_name VARCHAR(100) NOT NULL COMMENT '物料名称',
    material_spec VARCHAR(100) DEFAULT NULL COMMENT '规格',
    material_model VARCHAR(100) DEFAULT NULL COMMENT '型号',
    category_code VARCHAR(50) DEFAULT NULL COMMENT '品类编码',
    unit VARCHAR(20) DEFAULT NULL COMMENT '单位',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_material_code (material_code),
    KEY idx_name (material_name),
    KEY idx_category_status (category_code,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='物料主数据表';

CREATE TABLE rfq (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    rfq_no VARCHAR(50) NOT NULL COMMENT '询价单号',
    rfq_title VARCHAR(100) NOT NULL COMMENT '询价标题',
    org_id BIGINT DEFAULT NULL COMMENT '组织ID',
    currency VARCHAR(10) NOT NULL DEFAULT 'CNY' COMMENT '币种',
    quote_deadline DATETIME NOT NULL COMMENT '报价截止时间',
    rfq_status TINYINT NOT NULL DEFAULT 0 COMMENT '状态(0草稿,1已发布,2报价中,3已截止,4已定价,5已取消)',
    publish_time DATETIME DEFAULT NULL COMMENT '发布时间',
    close_time DATETIME DEFAULT NULL COMMENT '关闭时间',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_rfq_no (rfq_no),
    KEY idx_org_status_time (org_id,rfq_status,create_time),
    KEY idx_deadline (quote_deadline)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='询价单表';

CREATE TABLE rfq_item (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    rfq_id BIGINT NOT NULL COMMENT '询价单ID',
    line_no INT NOT NULL DEFAULT 0 COMMENT '行号',
    material_code VARCHAR(50) NOT NULL COMMENT '物料编码',
    material_name VARCHAR(100) NOT NULL COMMENT '物料名称',
    material_spec VARCHAR(100) DEFAULT NULL COMMENT '规格',
    unit VARCHAR(20) DEFAULT NULL COMMENT '单位',
    quantity DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '数量',
    target_delivery_date DATE DEFAULT NULL COMMENT '目标交期',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_rfq_id (rfq_id),
    KEY idx_material_code (material_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='询价明细表';

CREATE TABLE rfq_supplier (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    rfq_id BIGINT NOT NULL COMMENT '询价单ID',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    invite_status TINYINT NOT NULL DEFAULT 0 COMMENT '邀请状态(0待邀请,1已邀请,2已响应,3拒绝)',
    invite_time DATETIME DEFAULT NULL COMMENT '邀请时间',
    response_time DATETIME DEFAULT NULL COMMENT '响应时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_rfq_supplier (rfq_id,supplier_id),
    KEY idx_supplier_status (supplier_id,invite_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='询价邀请供应商表';

CREATE TABLE quote (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    quote_no VARCHAR(50) NOT NULL COMMENT '报价单号',
    rfq_id BIGINT NOT NULL COMMENT '询价单ID',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    currency VARCHAR(10) NOT NULL DEFAULT 'CNY' COMMENT '币种',
    exchange_rate DECIMAL(18,6) NOT NULL DEFAULT 1.000000 COMMENT '汇率',
    total_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '总金额',
    tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '税额',
    quote_status TINYINT NOT NULL DEFAULT 0 COMMENT '状态(0草稿,1已提交,2已采纳,3未采纳,4已撤回)',
    negotiation_round TINYINT NOT NULL DEFAULT 0 COMMENT '谈判轮次',
    payment_terms VARCHAR(100) DEFAULT NULL COMMENT '付款条件',
    submit_time DATETIME DEFAULT NULL COMMENT '提交时间',
    valid_until DATE DEFAULT NULL COMMENT '报价有效期',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_quote_no (quote_no),
    UNIQUE KEY uk_rfq_supplier (rfq_id,supplier_id),
    KEY idx_supplier_status (supplier_id,quote_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='报价单表';

CREATE TABLE quote_item (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    quote_id BIGINT NOT NULL COMMENT '报价单ID',
    rfq_item_id BIGINT NOT NULL COMMENT '询价明细ID',
    material_code VARCHAR(50) NOT NULL COMMENT '物料编码',
    quantity DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '数量',
    price DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '未税单价',
    tax_price DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '含税单价',
    tax_rate DECIMAL(10,4) NOT NULL DEFAULT 0.0000 COMMENT '税率',
    amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '未税金额',
    tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '税额',
    delivery_days INT DEFAULT NULL COMMENT '交货天数',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_quote_id (quote_id),
    KEY idx_rfq_item_id (rfq_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='报价明细表';

CREATE TABLE purchase_order (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    org_id BIGINT DEFAULT NULL COMMENT '组织ID',
    order_no VARCHAR(50) NOT NULL COMMENT '订单编号',
    erp_order_no VARCHAR(50) DEFAULT NULL COMMENT 'ERP订单号',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    supplier_name VARCHAR(100) DEFAULT NULL COMMENT '供应商名称',
    order_date DATE NOT NULL COMMENT '订单日期',
    delivery_date DATE DEFAULT NULL COMMENT '要求交货日期',
    currency VARCHAR(10) NOT NULL DEFAULT 'CNY' COMMENT '币种',
    exchange_rate DECIMAL(18,6) NOT NULL DEFAULT 1.000000 COMMENT '汇率',
    total_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '订单总金额',
    tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '税额',
    pay_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '应付金额',
    order_status TINYINT NOT NULL DEFAULT 0 COMMENT '订单状态(0待下发,1待确认,2已确认,3部分发货,4已完成,5已取消,6已拒单)',
    submit_time DATETIME DEFAULT NULL COMMENT '提交时间',
    confirm_time DATETIME DEFAULT NULL COMMENT '确认时间',
    reject_time DATETIME DEFAULT NULL COMMENT '拒单时间',
    close_time DATETIME DEFAULT NULL COMMENT '关闭时间',
    cancel_time DATETIME DEFAULT NULL COMMENT '取消时间',
    cancel_reason VARCHAR(500) DEFAULT NULL COMMENT '取消原因',
    buyer_id BIGINT DEFAULT NULL COMMENT '采购员ID',
    buyer_name VARCHAR(50) DEFAULT NULL COMMENT '采购员姓名',
    contract_no VARCHAR(50) DEFAULT NULL COMMENT '合同编号',
    payment_terms VARCHAR(255) DEFAULT NULL COMMENT '付款条款',
    delivery_address VARCHAR(255) DEFAULT NULL COMMENT '送货地址',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_no (order_no),
    KEY idx_supplier_status_date (supplier_id,order_status,order_date),
    KEY idx_org_status_create_time (org_id,order_status,create_time),
    KEY idx_erp_order_no (erp_order_no),
    KEY idx_delivery_date (delivery_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='采购订单主表';

CREATE TABLE purchase_order_detail (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    order_id BIGINT NOT NULL COMMENT '订单ID',
    order_no VARCHAR(50) DEFAULT NULL COMMENT '订单编号',
    line_no INT NOT NULL DEFAULT 0 COMMENT '行号',
    material_code VARCHAR(50) NOT NULL COMMENT '物料编码',
    material_name VARCHAR(100) NOT NULL COMMENT '物料名称',
    material_spec VARCHAR(100) DEFAULT NULL COMMENT '物料规格',
    material_model VARCHAR(100) DEFAULT NULL COMMENT '物料型号',
    unit VARCHAR(20) DEFAULT NULL COMMENT '单位',
    quantity DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '订单数量',
    price DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '未税单价',
    tax_price DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '含税单价',
    tax_rate DECIMAL(10,4) NOT NULL DEFAULT 0.0000 COMMENT '税率',
    amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '未税金额',
    tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '税额',
    delivered_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '已发货数量',
    received_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '已收货数量',
    qualified_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '合格数量',
    delivery_date DATE DEFAULT NULL COMMENT '要求交货日期',
    promise_date DATE DEFAULT NULL COMMENT '承诺交期',
    line_status TINYINT NOT NULL DEFAULT 0 COMMENT '行状态(0待确认,1已确认,2部分发货,3已完成,4已取消)',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_line (order_id,line_no),
    KEY idx_material_code (material_code),
    KEY idx_delivery_status (delivery_date,line_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='采购订单明细表';

CREATE TABLE delivery_plan (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    order_id BIGINT NOT NULL COMMENT '订单ID',
    order_detail_id BIGINT NOT NULL COMMENT '订单明细ID',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    plan_date DATE NOT NULL COMMENT '计划交付日期',
    plan_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '计划数量',
    promise_date DATE DEFAULT NULL COMMENT '承诺日期',
    plan_status TINYINT NOT NULL DEFAULT 0 COMMENT '状态(0待确认,1已确认,2已发货,3已完成,4已取消)',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_detail_date (order_detail_id,plan_date),
    KEY idx_supplier_status (supplier_id,plan_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='交付计划表';

CREATE TABLE order_change (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    change_no VARCHAR(50) NOT NULL COMMENT '变更单号',
    order_id BIGINT NOT NULL COMMENT '订单ID',
    order_detail_id BIGINT DEFAULT NULL COMMENT '订单明细ID',
    change_type TINYINT NOT NULL COMMENT '变更类型(1数量,2价格,3交期,4取消,5其他)',
    change_content VARCHAR(500) DEFAULT NULL COMMENT '变更内容',
    before_value VARCHAR(500) DEFAULT NULL COMMENT '变更前值',
    after_value VARCHAR(500) DEFAULT NULL COMMENT '变更后值',
    change_reason VARCHAR(500) DEFAULT NULL COMMENT '变更原因',
    approve_status TINYINT NOT NULL DEFAULT 0 COMMENT '审批状态(0待审批,1通过,2拒绝)',
    approve_by BIGINT DEFAULT NULL COMMENT '审批人',
    approve_time DATETIME DEFAULT NULL COMMENT '审批时间',
    approve_remark VARCHAR(500) DEFAULT NULL COMMENT '审批备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_change_no (change_no),
    KEY idx_order_status (order_id,approve_status),
    KEY idx_change_type (change_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='订单变更记录表';

CREATE TABLE order_status_log (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    order_id BIGINT NOT NULL COMMENT '订单ID',
    order_no VARCHAR(50) DEFAULT NULL COMMENT '订单编号',
    action_name VARCHAR(50) NOT NULL COMMENT '动作名称',
    before_status TINYINT DEFAULT NULL COMMENT '变更前状态',
    after_status TINYINT DEFAULT NULL COMMENT '变更后状态',
    operator_id BIGINT DEFAULT NULL COMMENT '操作人ID',
    operator_name VARCHAR(50) DEFAULT NULL COMMENT '操作人姓名',
    operate_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_order_time (order_id,operate_time),
    KEY idx_order_no (order_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='订单状态轨迹表';

CREATE TABLE order_track (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    order_id BIGINT NOT NULL COMMENT '订单ID',
    track_status TINYINT NOT NULL COMMENT '跟踪状态',
    track_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '跟踪时间',
    track_remark VARCHAR(500) DEFAULT NULL COMMENT '跟踪说明',
    operator BIGINT DEFAULT NULL COMMENT '操作人',
    operator_name VARCHAR(50) DEFAULT NULL COMMENT '操作人姓名',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_order_time (order_id,track_time),
    KEY idx_track_status (track_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='订单跟踪记录表';

CREATE TABLE delivery_notice (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    notice_no VARCHAR(50) NOT NULL COMMENT 'ASN单号',
    order_id BIGINT NOT NULL COMMENT '订单ID',
    order_no VARCHAR(50) DEFAULT NULL COMMENT '订单编号',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    supplier_name VARCHAR(100) DEFAULT NULL COMMENT '供应商名称',
    plan_delivery_date DATE DEFAULT NULL COMMENT '计划送货日期',
    actual_delivery_date DATE DEFAULT NULL COMMENT '实际送货日期',
    delivery_status TINYINT NOT NULL DEFAULT 0 COMMENT 'ASN状态(0草稿,1已提交,2在途,3部分收货,4已收货,5已取消)',
    delivery_method VARCHAR(50) DEFAULT NULL COMMENT '送货方式',
    delivery_company VARCHAR(100) DEFAULT NULL COMMENT '物流公司',
    delivery_no VARCHAR(50) DEFAULT NULL COMMENT '物流单号',
    driver_name VARCHAR(50) DEFAULT NULL COMMENT '司机姓名',
    driver_phone VARCHAR(20) DEFAULT NULL COMMENT '司机电话',
    vehicle_no VARCHAR(20) DEFAULT NULL COMMENT '车牌号',
    delivery_address VARCHAR(255) DEFAULT NULL COMMENT '送货地址',
    receiver VARCHAR(50) DEFAULT NULL COMMENT '收货人',
    receiver_phone VARCHAR(20) DEFAULT NULL COMMENT '收货人电话',
    batch_no VARCHAR(100) DEFAULT NULL COMMENT '批号',
    production_date DATE DEFAULT NULL COMMENT '生产日期',
    expiry_date DATE DEFAULT NULL COMMENT '有效期至',
    submit_time DATETIME DEFAULT NULL COMMENT '提交时间',
    send_time DATETIME DEFAULT NULL COMMENT '发货时间',
    arrive_time DATETIME DEFAULT NULL COMMENT '到达时间',
    close_time DATETIME DEFAULT NULL COMMENT '关闭时间',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_notice_no (notice_no),
    KEY idx_supplier_status_date (supplier_id,delivery_status,plan_delivery_date),
    KEY idx_order_id (order_id),
    KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='ASN送货通知单表';

CREATE TABLE delivery_detail (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    notice_id BIGINT NOT NULL COMMENT 'ASN ID',
    order_detail_id BIGINT DEFAULT NULL COMMENT '订单明细ID',
    material_code VARCHAR(50) NOT NULL COMMENT '物料编码',
    material_name VARCHAR(100) NOT NULL COMMENT '物料名称',
    material_spec VARCHAR(100) DEFAULT NULL COMMENT '物料规格',
    unit VARCHAR(20) DEFAULT NULL COMMENT '单位',
    plan_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '计划送货数量',
    actual_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '实际送货数量',
    received_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '已收货数量',
    qualified_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '合格数量',
    batch_no VARCHAR(50) DEFAULT NULL COMMENT '批次号',
    production_date DATE DEFAULT NULL COMMENT '生产日期',
    expiry_date DATE DEFAULT NULL COMMENT '过期日期/有效期至',
    box_count INT NOT NULL DEFAULT 0 COMMENT '箱数',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_notice_id (notice_id),
    KEY idx_order_detail_id (order_detail_id),
    KEY idx_material_code (material_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='ASN送货明细表';

CREATE TABLE delivery_label (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    label_no VARCHAR(50) NOT NULL COMMENT '标签编号',
    notice_id BIGINT NOT NULL COMMENT 'ASN ID',
    delivery_detail_id BIGINT DEFAULT NULL COMMENT 'ASN明细ID',
    material_code VARCHAR(50) DEFAULT NULL COMMENT '物料编码',
    batch_no VARCHAR(50) DEFAULT NULL COMMENT '批次号',
    package_no VARCHAR(50) DEFAULT NULL COMMENT '箱号',
    pallet_no VARCHAR(50) DEFAULT NULL COMMENT '托盘号',
    package_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '包装数量',
    qr_content VARCHAR(500) DEFAULT NULL COMMENT '二维码内容',
    print_count INT NOT NULL DEFAULT 0 COMMENT '打印次数',
    last_print_time DATETIME DEFAULT NULL COMMENT '最后打印时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_label_no (label_no),
    KEY idx_notice_id (notice_id),
    KEY idx_package_no (package_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='送货标签表';

CREATE TABLE receipt_record (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    receipt_no VARCHAR(50) NOT NULL COMMENT '收货单号',
    delivery_id BIGINT NOT NULL COMMENT '送货明细ID',
    notice_id BIGINT DEFAULT NULL COMMENT 'ASN ID',
    supplier_id BIGINT DEFAULT NULL COMMENT '供应商ID',
    material_code VARCHAR(50) NOT NULL COMMENT '物料编码',
    material_name VARCHAR(100) NOT NULL COMMENT '物料名称',
    plan_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '计划收货数量',
    receipt_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '实际收货数量',
    reject_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '拒收数量',
    receipt_time DATETIME DEFAULT NULL COMMENT '收货时间',
    receiver BIGINT DEFAULT NULL COMMENT '收货人',
    receiver_name VARCHAR(50) DEFAULT NULL COMMENT '收货人姓名',
    warehouse_id BIGINT DEFAULT NULL COMMENT '仓库ID',
    warehouse_name VARCHAR(100) DEFAULT NULL COMMENT '仓库名称',
    location VARCHAR(100) DEFAULT NULL COMMENT '库位',
    receipt_status TINYINT NOT NULL DEFAULT 0 COMMENT '状态(0待收货,1已收货,2已拒收,3部分收货)',
    diff_reason VARCHAR(500) DEFAULT NULL COMMENT '差异原因',
    reject_reason VARCHAR(500) DEFAULT NULL COMMENT '拒收原因',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_receipt_no (receipt_no),
    KEY idx_supplier_time (supplier_id,receipt_time),
    KEY idx_notice_id (notice_id),
    KEY idx_delivery_id (delivery_id),
    KEY idx_receipt_status (receipt_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='收货记录表';

CREATE TABLE vmi_inventory (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    material_code VARCHAR(50) NOT NULL COMMENT '物料编码',
    warehouse_id BIGINT DEFAULT NULL COMMENT '仓库ID',
    warehouse_name VARCHAR(100) DEFAULT NULL COMMENT '仓库名称',
    onhand_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '现有库存',
    available_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '可用库存',
    safety_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '安全库存',
    max_qty DECIMAL(18,4) DEFAULT NULL COMMENT '最高库存',
    inventory_status TINYINT NOT NULL DEFAULT 1 COMMENT '状态(1正常,2预警,3缺料)',
    last_sync_time DATETIME DEFAULT NULL COMMENT '最后同步时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_supplier_material_warehouse (supplier_id,material_code,warehouse_id),
    KEY idx_status (inventory_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='VMI库存表';

CREATE TABLE forecast_demand (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    demand_no VARCHAR(50) NOT NULL COMMENT '预测编号',
    supplier_id BIGINT DEFAULT NULL COMMENT '供应商ID',
    material_code VARCHAR(50) NOT NULL COMMENT '物料编码',
    demand_date DATE NOT NULL COMMENT '需求日期',
    demand_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '需求数量',
    demand_type TINYINT NOT NULL DEFAULT 1 COMMENT '需求类型(1预测,2JIT,3VMI补货)',
    demand_status TINYINT NOT NULL DEFAULT 0 COMMENT '状态(0待处理,1已发布,2已响应,3已关闭)',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_demand_no (demand_no),
    KEY idx_supplier_status_date (supplier_id,demand_status,demand_date),
    KEY idx_material_date (material_code,demand_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='需求预测表';

CREATE TABLE inspection_standard (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    standard_no VARCHAR(50) NOT NULL COMMENT '标准编号',
    material_code VARCHAR(50) NOT NULL COMMENT '物料编码',
    material_name VARCHAR(100) DEFAULT NULL COMMENT '物料名称',
    standard_name VARCHAR(100) NOT NULL COMMENT '检验标准名称',
    sample_rule VARCHAR(255) DEFAULT NULL COMMENT '抽样规则',
    inspection_strategy TINYINT DEFAULT 1 COMMENT '检验策略(0免检,1抽检,2全检)',
    sample_rate DECIMAL(5, 2) DEFAULT NULL COMMENT '抽检比例',
    acceptance_rate DECIMAL(5, 2) DEFAULT NULL COMMENT '合格标准率',
    version_no VARCHAR(20) DEFAULT NULL COMMENT '版本号',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态(0停用,1启用)',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_standard_no (standard_no),
    KEY idx_material_status (material_code,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='检验标准表';

CREATE TABLE inspection_standard_item (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    standard_id BIGINT NOT NULL COMMENT '标准ID',
    item_name VARCHAR(100) NOT NULL COMMENT '检验项目',
    item_type TINYINT NOT NULL DEFAULT 1 COMMENT '项目类型(1定性,2定量)',
    standard_value VARCHAR(255) DEFAULT NULL COMMENT '标准值',
    upper_limit DECIMAL(18,4) DEFAULT NULL COMMENT '上限',
    lower_limit DECIMAL(18,4) DEFAULT NULL COMMENT '下限',
    unit VARCHAR(20) DEFAULT NULL COMMENT '单位',
    required TINYINT NOT NULL DEFAULT 1 COMMENT '是否必检',
    sort INT NOT NULL DEFAULT 0 COMMENT '排序',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_standard_sort (standard_id,sort)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='检验标准项目表';

CREATE TABLE quality_inspection (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    inspection_no VARCHAR(50) NOT NULL COMMENT '检验单号',
    receipt_id BIGINT NOT NULL COMMENT '收货记录ID',
    delivery_id BIGINT DEFAULT NULL COMMENT '送货明细ID',
    supplier_id BIGINT DEFAULT NULL COMMENT '供应商ID',
    material_code VARCHAR(50) NOT NULL COMMENT '物料编码',
    material_name VARCHAR(100) NOT NULL COMMENT '物料名称',
    inspect_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '检验数量',
    qualified_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '合格数量',
    unqualified_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '不合格数量',
    inspect_result TINYINT NOT NULL DEFAULT 0 COMMENT '检验结果(0待检,1合格,2不合格,3部分合格)',
    inspect_type TINYINT NOT NULL DEFAULT 1 COMMENT '检验类型',
    inspect_time DATETIME DEFAULT NULL COMMENT '检验时间',
    inspector BIGINT DEFAULT NULL COMMENT '检验员',
    inspector_name VARCHAR(50) DEFAULT NULL COMMENT '检验员姓名',
    inspect_remark VARCHAR(500) DEFAULT NULL COMMENT '检验说明',
    handle_method TINYINT DEFAULT NULL COMMENT '处理方式(1退货,2换货,3特采,4报废,5扣款)',
    handle_remark VARCHAR(500) DEFAULT NULL COMMENT '处理说明',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_inspection_no (inspection_no),
    KEY idx_supplier_result_time (supplier_id,inspect_result,inspect_time),
    KEY idx_receipt_id (receipt_id),
    KEY idx_material_code (material_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='质量检验表';

CREATE TABLE nonconformance_report (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    ncr_no VARCHAR(50) NOT NULL COMMENT 'NCR单号',
    inspection_id BIGINT DEFAULT NULL COMMENT '检验单ID',
    receipt_id BIGINT DEFAULT NULL COMMENT '收货记录ID',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    material_code VARCHAR(50) DEFAULT NULL COMMENT '物料编码',
    material_name VARCHAR(100) DEFAULT NULL COMMENT '物料名称',
    unqualified_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '不合格数量',
    problem_desc TEXT NOT NULL COMMENT '问题描述',
    severity TINYINT NOT NULL DEFAULT 1 COMMENT '严重等级(1一般,2严重,3重大)',
    handle_method TINYINT DEFAULT NULL COMMENT '处理方式',
    ncr_status TINYINT NOT NULL DEFAULT 0 COMMENT '状态(0草稿,1已发布,2处理中,3待验证,4已关闭,5已取消)',
    submit_time DATETIME DEFAULT NULL COMMENT '提交时间',
    close_time DATETIME DEFAULT NULL COMMENT '关闭时间',
    close_remark VARCHAR(500) DEFAULT NULL COMMENT '关闭说明',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_ncr_no (ncr_no),
    KEY idx_supplier_status_time (supplier_id,ncr_status,create_time),
    KEY idx_inspection_id (inspection_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='NCR质量异常表';

CREATE TABLE eight_d_report (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    report_no VARCHAR(50) NOT NULL COMMENT '8D报告编号',
    ncr_id BIGINT NOT NULL COMMENT 'NCR ID',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    d1_team TEXT DEFAULT NULL COMMENT 'D1团队',
    d2_problem TEXT DEFAULT NULL COMMENT 'D2问题描述',
    d3_containment TEXT DEFAULT NULL COMMENT 'D3遏制措施',
    d4_root_cause TEXT DEFAULT NULL COMMENT 'D4根因分析',
    d5_corrective_action TEXT DEFAULT NULL COMMENT 'D5纠正措施',
    d6_validate_action TEXT DEFAULT NULL COMMENT 'D6验证措施',
    d7_prevent_action TEXT DEFAULT NULL COMMENT 'D7预防措施',
    d8_close_summary TEXT DEFAULT NULL COMMENT 'D8关闭总结',
    due_date DATE DEFAULT NULL COMMENT '截止日期',
    report_status TINYINT NOT NULL DEFAULT 0 COMMENT '状态(0草稿,1已提交,2审核中,3退回,4已关闭)',
    submit_time DATETIME DEFAULT NULL COMMENT '提交时间',
    audit_time DATETIME DEFAULT NULL COMMENT '审核时间',
    close_time DATETIME DEFAULT NULL COMMENT '关闭时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_report_no (report_no),
    UNIQUE KEY uk_ncr_id (ncr_id),
    KEY idx_supplier_status_due (supplier_id,report_status,due_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='8D整改报告表';

CREATE TABLE appeal (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    appeal_no VARCHAR(50) NOT NULL COMMENT '申诉编号',
    ncr_id BIGINT DEFAULT NULL COMMENT 'NCR ID',
    inspection_id BIGINT DEFAULT NULL COMMENT '检验单ID',
    deduction_id BIGINT DEFAULT NULL COMMENT '扣款单ID',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    material_code VARCHAR(50) DEFAULT NULL COMMENT '物料编码',
    material_name VARCHAR(100) DEFAULT NULL COMMENT '物料名称',
    appeal_reason TEXT NOT NULL COMMENT '申诉原因',
    appeal_desc VARCHAR(500) DEFAULT NULL COMMENT '申诉说明',
    adjust_amount DECIMAL(18, 2) DEFAULT NULL COMMENT '调整金额',
    appeal_status TINYINT NOT NULL DEFAULT 0 COMMENT '状态(0草稿,1已提交,2审核通过,3审核驳回)',
    submit_time DATETIME DEFAULT NULL COMMENT '提交时间',
    reviewer BIGINT DEFAULT NULL COMMENT '审核人',
    reviewer_name VARCHAR(100) DEFAULT NULL COMMENT '审核人姓名',
    review_time DATETIME DEFAULT NULL COMMENT '审核时间',
    review_opinion VARCHAR(500) DEFAULT NULL COMMENT '审核意见',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_appeal_no (appeal_no),
    KEY idx_supplier_status_time (supplier_id, appeal_status, create_time),
    KEY idx_ncr_id (ncr_id),
    KEY idx_deduction_id (deduction_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='质检申诉联动扣款表';

CREATE TABLE quality_appeal (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    appeal_no VARCHAR(50) NOT NULL COMMENT '申诉编号',
    ncr_id BIGINT DEFAULT NULL COMMENT 'NCR ID',
    inspection_id BIGINT DEFAULT NULL COMMENT '检验单ID',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    appeal_reason TEXT NOT NULL COMMENT '申诉原因',
    appeal_status TINYINT NOT NULL DEFAULT 0 COMMENT '状态(0草稿,1已提交,2审核中,3通过,4驳回)',
    submit_time DATETIME DEFAULT NULL COMMENT '提交时间',
    audit_by BIGINT DEFAULT NULL COMMENT '审核人',
    audit_time DATETIME DEFAULT NULL COMMENT '审核时间',
    audit_remark VARCHAR(500) DEFAULT NULL COMMENT '审核备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_appeal_no (appeal_no),
    KEY idx_supplier_status_time (supplier_id,appeal_status,create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='质量申诉表';

CREATE TABLE reconciliation (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    recon_no VARCHAR(50) NOT NULL COMMENT '对账单号',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    supplier_name VARCHAR(100) DEFAULT NULL COMMENT '供应商名称',
    recon_period VARCHAR(20) NOT NULL COMMENT '对账周期',
    start_date DATE DEFAULT NULL COMMENT '开始日期',
    end_date DATE DEFAULT NULL COMMENT '结束日期',
    total_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '对账总金额',
    confirmed_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '确认金额',
    diff_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '差异金额',
    recon_status TINYINT NOT NULL DEFAULT 0 COMMENT '状态(0草稿,1待供应商确认,2供应商已确认,3有异议,4已开票,5已付款,6已关闭)',
    send_time DATETIME DEFAULT NULL COMMENT '发送时间',
    confirm_time DATETIME DEFAULT NULL COMMENT '确认时间',
    confirm_by BIGINT DEFAULT NULL COMMENT '确认人',
    close_time DATETIME DEFAULT NULL COMMENT '关闭时间',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_recon_no (recon_no),
    KEY idx_supplier_status_period (supplier_id,recon_status,recon_period),
    KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='对账单表';

CREATE TABLE reconciliation_detail (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    recon_id BIGINT NOT NULL COMMENT '对账单ID',
    order_id BIGINT DEFAULT NULL COMMENT '订单ID',
    order_no VARCHAR(50) DEFAULT NULL COMMENT '订单编号',
    receipt_id BIGINT DEFAULT NULL COMMENT '收货ID',
    receipt_no VARCHAR(50) DEFAULT NULL COMMENT '收货单号',
    material_code VARCHAR(50) DEFAULT NULL COMMENT '物料编码',
    material_name VARCHAR(100) DEFAULT NULL COMMENT '物料名称',
    quantity DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '数量',
    unit_price DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '单价',
    order_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '订单金额',
    deduction_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '扣款金额',
    confirmed_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '确认金额',
    diff_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '差异金额',
    diff_reason VARCHAR(500) DEFAULT NULL COMMENT '差异原因',
    confirm_status TINYINT NOT NULL DEFAULT 0 COMMENT '确认状态(0待确认,1已确认,2有异议)',
    confirm_time DATETIME DEFAULT NULL COMMENT '确认时间',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_recon_id (recon_id),
    KEY idx_order_id (order_id),
    KEY idx_receipt_id (receipt_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='对账明细表';

CREATE TABLE deduction (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    deduction_no VARCHAR(50) NOT NULL COMMENT '扣款单号',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    source_type VARCHAR(50) NOT NULL COMMENT '来源类型',
    source_id BIGINT DEFAULT NULL COMMENT '来源ID',
    deduction_type TINYINT NOT NULL COMMENT '扣款类型(1质量,2延期,3短交,4其他)',
    deduction_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '扣款金额',
    deduction_reason VARCHAR(500) NOT NULL COMMENT '扣款原因',
    deduction_status TINYINT NOT NULL DEFAULT 0 COMMENT '状态(0草稿,1已提交,2已确认,3有异议,4已入账)',
    recon_id BIGINT DEFAULT NULL COMMENT '对账单ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_deduction_no (deduction_no),
    KEY idx_supplier_status_time (supplier_id,deduction_status,create_time),
    KEY idx_source (source_type,source_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='扣款单表';

CREATE TABLE invoice (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    invoice_no VARCHAR(50) NOT NULL COMMENT '发票号码',
    invoice_code VARCHAR(50) DEFAULT NULL COMMENT '发票代码',
    invoice_type TINYINT NOT NULL DEFAULT 1 COMMENT '发票类型',
    recon_id BIGINT DEFAULT NULL COMMENT '对账单ID',
    supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    supplier_name VARCHAR(100) DEFAULT NULL COMMENT '供应商名称',
    tax_number VARCHAR(50) DEFAULT NULL COMMENT '税号',
    invoice_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '发票金额',
    tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '税额',
    tax_rate DECIMAL(10,4) NOT NULL DEFAULT 0.0000 COMMENT '税率',
    invoice_date DATE DEFAULT NULL COMMENT '开票日期',
    invoice_status TINYINT NOT NULL DEFAULT 0 COMMENT '状态(0待开票,1已上传,2已验真,3已认证,4已作废)',
    receive_time DATETIME DEFAULT NULL COMMENT '收到时间',
    certify_time DATETIME DEFAULT NULL COMMENT '认证时间',
    void_time DATETIME DEFAULT NULL COMMENT '作废时间',
    void_reason VARCHAR(500) DEFAULT NULL COMMENT '作废原因',
    file_id BIGINT DEFAULT NULL COMMENT '发票附件ID',
    ocr_status TINYINT NOT NULL DEFAULT 0 COMMENT 'OCR状态(0未识别,1识别中,2成功,3失败)',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_invoice_tax (invoice_no,tax_number),
    KEY idx_recon_id (recon_id),
    KEY idx_supplier_status_date (supplier_id,invoice_status,invoice_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='发票表';

CREATE TABLE payment (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    payment_no VARCHAR(50) NOT NULL COMMENT '付款单号',
    invoice_id BIGINT DEFAULT NULL COMMENT '发票ID',
    invoice_no VARCHAR(50) DEFAULT NULL COMMENT '发票号码',
    supplier_id BIGINT DEFAULT NULL COMMENT '供应商ID',
    supplier_name VARCHAR(100) DEFAULT NULL COMMENT '供应商名称',
    payment_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '付款金额',
    payment_method TINYINT NOT NULL DEFAULT 1 COMMENT '付款方式',
    payment_account VARCHAR(50) DEFAULT NULL COMMENT '付款账号',
    payment_bank VARCHAR(100) DEFAULT NULL COMMENT '付款银行',
    receive_account VARCHAR(50) DEFAULT NULL COMMENT '收款账号',
    receive_bank VARCHAR(100) DEFAULT NULL COMMENT '收款银行',
    payment_time DATETIME DEFAULT NULL COMMENT '付款时间',
    payment_status TINYINT NOT NULL DEFAULT 0 COMMENT '付款状态(0待付款,1部分付款,2已付款,3已拒绝)',
    receipt_no VARCHAR(100) DEFAULT NULL COMMENT '外部付款回执号',
    approve_status TINYINT NOT NULL DEFAULT 0 COMMENT '审批状态',
    voucher_no VARCHAR(50) DEFAULT NULL COMMENT '凭证号',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_payment_no (payment_no),
    UNIQUE KEY uk_receipt_no (receipt_no),
    KEY idx_supplier_status_time (supplier_id,payment_status,payment_time),
    KEY idx_invoice_id (invoice_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='付款记录表';

CREATE TABLE portal_todo (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    user_id BIGINT DEFAULT NULL COMMENT '用户ID',
    supplier_id BIGINT DEFAULT NULL COMMENT '供应商ID',
    todo_type VARCHAR(50) NOT NULL COMMENT '待办类型',
    business_type VARCHAR(50) NOT NULL COMMENT '业务类型',
    business_id BIGINT NOT NULL COMMENT '业务ID',
    business_no VARCHAR(50) DEFAULT NULL COMMENT '业务单号',
    title VARCHAR(200) NOT NULL COMMENT '标题',
    todo_status TINYINT NOT NULL DEFAULT 0 COMMENT '状态(0待办,1已办,2忽略)',
    due_time DATETIME DEFAULT NULL COMMENT '截止时间',
    finish_time DATETIME DEFAULT NULL COMMENT '完成时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_user_status_time (user_id,todo_status,create_time),
    KEY idx_supplier_status_time (supplier_id,todo_status,create_time),
    KEY idx_business (business_type,business_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='门户待办表';

CREATE TABLE message_notice (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    notice_no VARCHAR(50) NOT NULL COMMENT '通知编号',
    receiver_user_id BIGINT DEFAULT NULL COMMENT '接收用户ID',
    receiver_supplier_id BIGINT DEFAULT NULL COMMENT '接收供应商ID',
    channel TINYINT NOT NULL DEFAULT 1 COMMENT '通道(1站内信,2邮件,3短信,4企微)',
    title VARCHAR(200) NOT NULL COMMENT '标题',
    content TEXT NOT NULL COMMENT '内容',
    business_type VARCHAR(50) DEFAULT NULL COMMENT '业务类型',
    business_id BIGINT DEFAULT NULL COMMENT '业务ID',
    send_status TINYINT NOT NULL DEFAULT 0 COMMENT '发送状态(0待发送,1成功,2失败)',
    read_status TINYINT NOT NULL DEFAULT 0 COMMENT '阅读状态(0未读,1已读)',
    send_time DATETIME DEFAULT NULL COMMENT '发送时间',
    read_time DATETIME DEFAULT NULL COMMENT '阅读时间',
    retry_count INT NOT NULL DEFAULT 0 COMMENT '重试次数',
    error_message VARCHAR(500) DEFAULT NULL COMMENT '错误信息',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_notice_no (notice_no),
    KEY idx_user_read_time (receiver_user_id,read_status,create_time),
    KEY idx_supplier_time (receiver_supplier_id,create_time),
    KEY idx_business (business_type,business_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='消息通知表';

CREATE TABLE message_event_log (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    event_id VARCHAR(100) NOT NULL COMMENT '事件ID',
    event_type VARCHAR(100) NOT NULL COMMENT '事件类型',
    source VARCHAR(100) NOT NULL DEFAULT 'supplier-collaboration' COMMENT '事件来源',
    trace_id VARCHAR(100) DEFAULT NULL COMMENT '链路ID',
    business_type VARCHAR(50) DEFAULT NULL COMMENT '业务类型',
    business_id BIGINT DEFAULT NULL COMMENT '业务ID',
    business_no VARCHAR(50) DEFAULT NULL COMMENT '业务单号',
    payload JSON DEFAULT NULL COMMENT '事件内容',
    publish_status TINYINT NOT NULL DEFAULT 0 COMMENT '发布状态(0待发布,1成功,2失败)',
    consume_status TINYINT NOT NULL DEFAULT 0 COMMENT '消费状态(0待消费,1成功,2失败,3忽略)',
    retry_count INT NOT NULL DEFAULT 0 COMMENT '重试次数',
    error_message VARCHAR(500) DEFAULT NULL COMMENT '错误信息',
    occurred_at DATETIME NOT NULL COMMENT '发生时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_event_id (event_id),
    KEY idx_event_status_time (event_type,publish_status,create_time),
    KEY idx_business (business_type,business_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='事件消息日志表';

CREATE TABLE integration_endpoint (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    endpoint_code VARCHAR(50) NOT NULL COMMENT '端点编码',
    endpoint_name VARCHAR(100) NOT NULL COMMENT '端点名称',
    system_type VARCHAR(50) NOT NULL COMMENT '系统类型(ERP,WMS,MES,FINANCE,OCR)',
    integration_mode VARCHAR(50) NOT NULL COMMENT '集成方式(REST,MQ,FILE,DB,EDI)',
    base_url VARCHAR(500) DEFAULT NULL COMMENT '基础地址',
    auth_type VARCHAR(50) DEFAULT NULL COMMENT '认证类型',
    timeout_ms INT NOT NULL DEFAULT 30000 COMMENT '超时时间毫秒',
    retry_limit INT NOT NULL DEFAULT 3 COMMENT '重试次数',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_endpoint_code (endpoint_code),
    KEY idx_system_status (system_type,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='集成端点配置表';

CREATE TABLE integration_log (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    trace_id VARCHAR(100) DEFAULT NULL COMMENT '链路ID',
    endpoint_code VARCHAR(50) DEFAULT NULL COMMENT '端点编码',
    system_type VARCHAR(50) NOT NULL COMMENT '系统类型',
    interface_code VARCHAR(100) NOT NULL COMMENT '接口编码',
    direction TINYINT NOT NULL COMMENT '方向(1入站,2出站)',
    business_type VARCHAR(50) DEFAULT NULL COMMENT '业务类型',
    business_id BIGINT DEFAULT NULL COMMENT '业务ID',
    request_summary TEXT DEFAULT NULL COMMENT '请求摘要',
    response_summary TEXT DEFAULT NULL COMMENT '响应摘要',
    result_status TINYINT NOT NULL DEFAULT 0 COMMENT '结果(0失败,1成功)',
    error_message VARCHAR(500) DEFAULT NULL COMMENT '错误信息',
    cost_ms INT DEFAULT NULL COMMENT '耗时毫秒',
    retry_count INT NOT NULL DEFAULT 0 COMMENT '重试次数',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_interface_status_time (interface_code,result_status,create_time),
    KEY idx_business (business_type,business_id),
    KEY idx_trace_id (trace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='集成调用日志表';

CREATE TABLE integration_sync_task (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    task_no VARCHAR(50) NOT NULL COMMENT '同步任务号',
    system_type VARCHAR(50) NOT NULL COMMENT '系统类型',
    task_type VARCHAR(50) NOT NULL COMMENT '任务类型',
    external_no VARCHAR(100) DEFAULT NULL COMMENT '外部单号',
    event_type VARCHAR(100) DEFAULT NULL COMMENT '事件类型',
    payload JSON DEFAULT NULL COMMENT '任务内容',
    task_status TINYINT NOT NULL DEFAULT 0 COMMENT '状态(0待处理,1处理中,2成功,3失败,4忽略)',
    retry_count INT NOT NULL DEFAULT 0 COMMENT '重试次数',
    next_retry_time DATETIME DEFAULT NULL COMMENT '下次重试时间',
    error_message VARCHAR(500) DEFAULT NULL COMMENT '错误信息',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_no (task_no),
    UNIQUE KEY uk_external_event (external_no,event_type),
    KEY idx_type_status_time (task_type,task_status,create_time),
    KEY idx_retry_time (next_retry_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='集成同步任务表';

CREATE TABLE biz_status_track (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    business_type VARCHAR(50) NOT NULL COMMENT '业务类型(delivery_notice/quality_inspection/reconciliation/receipt_record)',
    business_id BIGINT NOT NULL COMMENT '业务ID',
    before_status TINYINT DEFAULT NULL COMMENT '变更前状态',
    after_status TINYINT COMMENT '变更后状态',
    track_remark VARCHAR(500) DEFAULT NULL COMMENT '轨迹说明',
    operator BIGINT DEFAULT NULL COMMENT '操作人',
    operator_name VARCHAR(50) DEFAULT NULL COMMENT '操作人姓名',
    operate_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    KEY idx_business (business_type, business_id),
    KEY idx_operator_time (operator, operate_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='通用业务状态轨迹表';

SET FOREIGN_KEY_CHECKS = 1;
